# Site settings
title: Fully Studios
email: hello@fullystudios.se
tel: "+46 738 07 30 72"
description: Fully Studios creates technical and visual identities for brands and services around the world.
adress-gbg: Victoriapassagen,<br>Södra Larmgatan 14,<br>411 16 Göteborg
adress-sthlm: Högbergsgatan 33,<br>116 20 Stockholm
navigate-url-gbg: "https://www.google.se/maps/place/Fully+Studios/@57.7033354,11.9634248,17z/data=!3m1!4b1!4m5!3m4!1s0x464ff365f9958667:0xc960c81a24202e95!8m2!3d57.7033354!4d11.9656134"
fully_gbg-lat: 57.703229
fully_gbg-lng: 11.965552
fully_sthlm-lat: 59.316565
fully_sthlm-lng: 18.072738

navigate-url-sthlm: "https://www.google.com/maps/dir//H%C3%B6gbergsgatan+33,+116+20+Stockholm/@59.3165393,18.0706036,17z/data=!4m9!4m8!1m0!1m5!1m1!1s0x465f77fae124b625:0xef7a13a957087b12!2m2!1d18.0727509!2d59.316577!3e3"

baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/fullystudios.github.io/public/" # for demo site on demo.fullyflared.se/fullystudios
url: "https://fullystudios.se" # the base hostname & protocol for your site
absolute_path: "https://fullystudios.se" # should be https://fullystudios.se on the live site
shareimage: "images/fully-studios-facebook-share-image-v2.png"
twitter: "https://twitter.com/fullyflared_se"
github:  "https://github.com/fullystudios"
facebook: "https://www.facebook.com/fullystudios/"
vimeo: "https://vimeo.com/fullystudios"
instagram: "https://www.instagram.com/fullystudios/"

# Current news
# herofile: three-houses.html
herofile: fully-hero.html

# herojsfile: fully-hero.js

# UI copy
morenews: "More news"

# Collector: 1
# Tanumstrand: 2
# Papricaklubben: 5
# Pågen: 8
# Svenska skolan: 9
# Qgroup: 10
# Brooklyn 12

case_highlight1_id: 11

case_highlight2_id: 5

case_highlight3_id: 12

# Links
works: "/work"
about: "/about"
curiosities: "/curiosities"

# Custom post types
collections:
  work:
    output: true
    permalink: /:collection/:title/
  curious-about:
    output: true
    permalink: /:collection/:title/
  news:
    output: true
    permalink: /:collection/:title/


# Default values
defaults:
  -
    scope:
      path: ""
      type: "curious-about"
    values:
      layout: "curious"
      button-text: Read all about it
      background-color: "#f8f8f8"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      button-text: View case
      background-color: "#f8f8f8"
  -
    scope:
      path: ""
      type: "news"
    values:
      layout: "news"
      button-text: View news
      background-color: "#f8f8f8"

# Build settings
highlighter: rouge
markdown: kramdown
source: src
destination: public
sass:
  sass_dir: assets/css/modules
  style: compressed

# live reload
livereload: true # false on production
reload_port: 5678

# gems
plugins_dir:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-redirect-from

# plugin settings
autoprefixer:
  browsers:
  - last 3 versions
  - ios_saf 9
  - ios_saf 8
  - ios_saf 7
  - IE 11

exclude: ['node_modules', 'webpack', 'Gemfile', 'Gemfile.lock', 'Rakefile']
