# Site settings
title: Fully Studios
email: hello@fullystudios.se
tel: "+46 738 07 30 72"
description: Fully Studios is a Swedish web and film studio, specializing in motion on the web.
adress-gbg: Victoriapassagen,<br>Södra Larmgatan 14,<br>411 16 Göteborg
adress-sthlm: Garage 56,<br>Brännkyrkagatan 56,<br>118 22 Stockholm
baseurl: "" # the subpath of your site, e.g. /blog
# baseurl: "/fullystudios.github.io/public/" # for demo site on demo.fullyflared.se/fullystudios
url: "https://fullystudios.se" # the base hostname & protocol for your site
absolute_path: "https://fullystudios.se" # should be https://fullystudios.se on the live site
shareimage: "images/fully-studios-facebook-share-image-v2.png"
twitter: "https://twitter.com/fullyflared_se"
github:  "https://github.com/fullystudios"
facebook: "https://www.facebook.com/fullystudios/"
vimeo: "https://vimeo.com/fullystudios"
instagram: "https://www.instagram.com/fullystudios/"
newsflash: |
  ### Our Stockholm office is open!

  We now have offices on both coasts and want to make new friends.
  Stockholmers, hit us up! We’ll bring you a snack from the onboard bistro.

newsflash_buttontext: Contact Sthlm office
newsflash_buttonurl: mailto:joakim.hanner@fullystudios.se

# Papricaklubben
case_highlight1_id: 5

# Collector
case_highlight2_id: 1

# Tanumstrand
case_highlight3_id: 2

# Links
works: "/work"
about: "/about"
curiousities: "/curiousities"

# Custom post types 
collections:
  work:
    output: true
    permalink: /:collection/:title/
  curious-about:
    output: true
    permalink: /:collection/:title/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "curious-about"
    values:
      layout: "curious"
      button-text: Read all about it
      background-color: "#f8f8f8"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      button-text: View case
      background-color: "#f8f8f8"

# Build settings
highlighter: rouge
markdown: kramdown
source: src
destination: public
sass:
  sass_dir: assets/css/modules
  style: compressed

# live reload
# livereload: false # false on production
# reload_port: 5678

# gems
plugins_dir:
  - jekyll-seo-tag
  - jekyll-autoprefixer
  - jekyll-sitemap
  - jekyll-redirect-from

# plugin settings
autoprefixer:
  browsers:
  - last 3 versions
  - ios_saf 9
  - ios_saf 8
  - ios_saf 7

exclude: ['node_modules', 'webpack', 'Gemfile', 'Gemfile.lock', 'Rakefile']
